### ISSUE TITLE
Not working on a specific site

### ISSUE THREAD

**Issue by carlsednaoui** [carlsednaoui/seo-bookmarklet#1]
OuiSEO does not work on this site: http://www.frankwatching.com/archive/2013/08/08/verbeter-je-site-vijf-praktische-manieren-voor-gebruikersonderzoek/

Find out why.

**Comment by csi-lk** [comment]
Looks like jQuery is loaded on your site but you are not using the `$` alias

**Comment by carlsednaoui** [comment]
Correct. Old issue, will close. Thanks @Si1kIfY
