### ISSUE TITLE
Install page doesnt works

### ISSUE THREAD

**Issue by olhapi** [carlsednaoui/seo-bookmarklet#5]

**Comment by carlsednaoui** [comment]
It does, just tested it.

**Comment by olhapi** [comment]
Ok, the page doesnt work from link here http://moz.com/ugc/a-onestop-seo-bookmarklet-that-includes-social-metadata
This link  doesnt work: http://carlsednaoui.github.io/ouiseo/install.html

**Comment by carlsednaoui** [comment]
omg, thanks for the note @puagardian! I'll go update it now :)
